# Page unique id, see scripts/helper.js#page_uid()
# 页面唯一id设置，影响到评论等第三方系统，页面唯一id的原始值为页面的当前路径
page_uid:
  hash: true # 是否加密，加密后的uid没有特殊字符，推荐使用此项。
  combined: true #是否合并多语言uid，true则多语言页面使用相同的uid
# 当文章有修改时，是否在标题后面显示“new”并且高亮最后修改日期
page_new: false

# script and css，站点使用的全局脚本及css文件
js_css:
- url: //cdn.bootcss.com/jquery/2.2.0/jquery.min.js #jquery
- url: //cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css
- url: //cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css
- url: //cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js
#- url: //cdn.staticfile.org/bootstrap-material-design/0.5.10/css/bootstrap-material-design.min.css
#- url: //cdn.staticfile.org/bootstrap-material-design/0.5.10/css/ripples.min.css
#- url: //cdn.staticfile.org/bootstrap-material-design/0.5.10/js/material.min.js
#- url: //cdn.staticfile.org/bootstrap-material-design/0.5.10/js/ripples.min.js
- url: //cdn.staticfile.org/sidr/2.2.1/jquery.sidr.min.js
- url: js/jquery.bootstrap-autohidingnavbar.min.js
- url: //cdn.staticfile.org/sidr/2.2.1/stylesheets/jquery.sidr.dark.min.css
- url: //cdn.staticfile.org/highlight.js/9.15.10/styles/github.min.css
- url: //cdn.staticfile.org/highlight.js/9.15.10/highlight.min.js
- url: //cdn.jsdelivr.net/gh/tonsky/FiraCode@2/distr/fira_code.css
- url: //cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
- url: //cdn.staticfile.org/fancybox/2.1.5/jquery.fancybox.pack.js
- url: //cdn.staticfile.org/fancybox/2.1.5/jquery.fancybox.min.css
- url: //cdn.staticfile.org/fancybox/2.1.5/helpers/jquery.fancybox-buttons.css
- url: //cdn.staticfile.org/fancybox/2.1.5/helpers/jquery.fancybox-buttons.js
- url: //cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css
- url: //cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css
- url: css/nova_font.css
- url: css/bs/nova.css
- url: //unpkg.com/leancloud-storage@4.13.2/dist/av-min.js
- url: js/leancloud.js

# menu, all menu name must be translated, see language/lang.yml
# 主菜单，
menu:
- name: home # 首页
  url: /
- name: project # 项目，需hexo-generator-github插件及github配置
  url: /p/
- name: category # 分类
  url: /categories/
- name: archive # 归档
  url: /archives/
- name: donate # 打赏列表，需lc支持，并创建Donate表
  url: /donate/
- name: about # 关于
  url: /about/

# post widgets. see layout/post/widget_xxx.swig
# 首页右侧边栏小部件
post_widgets:
  - search #搜索
  - announce #公告，需要lc的支持，Config表中配置name=announce,value就是内容
#  - ds_recent_visitors
  - about # 关于
  - category # 文章分类
  - tag # 文章标签云
#  - archive #文章归档
#  - recent_posts #最新文章
  - top_views # 热点文章
#  - cy_hot_news
#  - cy_hot_users
  - recent_comments # 最近评论
  - links #友情链接

# TODO fetch widgets use ajax, widgets e.g. tag, archive, is sample in all pages.
# used ajax to get widget_xxx contents dynamicly to avoid change all pages.
#
post_widgets_animate: 'animated slideInUp faster'
post_widgets_ajax: true
post_widgets_show_count: true
post_widgets_recent_count: 5
# widget links, url is required, name and icon is optional, the icon can be relative or absolute path.
post_widgets_links:
  - name: Jamling's Blog
    url: http://life.ieclipse.cn
    icon: /image/logo.png
  - name: 生辰助手
    url: //www.ieclipse.cn/birthday-tool/
    icon: //www.ieclipse.cn/birthday-tool/image.png

# about
about:
  name: Jamling
  github: Jamling
  email: li.jamling@gmail.com
  twitter: JamlingLi
  weibo: Jamling
  desc: 欢迎点击以下图标关注我或与我互动！

# archive
archive:
  type: yearly #yearly|monthly(defaut) see list_archives options
  order: -1 # 1(asc)|-1(desc) defaut desc
  format: YYYY
  show_count: false # true|false, defaut true
  amount: 5 # amount in post widgets

# toc
toc:
  post: true
  project: true
  page: true
# donate
donate:
  enable: true # whether enable page donate

# github removed see hexo-generator-github.

##评论功能设置，建议使用畅言
comments:
  enable: true
  using: valine
  valine: # Valine
    app_id: your_leancloud_app_id
    app_key: your_leancloud_app_key
    visitor: false #是否支持文章阅读数，建议关闭此项，开启lc
    url: your_leancloud_domain

# 开启LeanCloud公告、文章阅读计数、打赏等功能
# Counter阅读计数表：time:Number阅读数，title：文章标题, url：文章链接，xid：页面唯一id
# Comment评论表表：参考valine，会自动生成,本主题扩展了一个title字段
# Config配置表：name:String参数名，value：String参数值，tag：String标签，type:String类型
# config表，name=visitors表示总访问数，name=announce,type=html，表示公告，内容类型为html
# Donate捐赠表：amount:Number金额，
lc:
  enable: true # true|false 总开关
  class: Counter # leanclound上的class名称
  app_id: your_leancloud_app_id
  app_key: your_leancloud_app_key
  url: your_leancloud_domain # //lc.ieclipse.cn
  visitors_index: home # home|total (首页阅读量|总阅读量)


## share
share:
  footer:
    enable: true #开启文章末尾分享
    layout: share_js #portial 下的分享模板名称
## 站点分析统计代码功能组件，本主题提供了google统计和baidu统计
analytics:
  enable: false #小网站要个毛统计！
  using: baidu
  baidu:
    id: 
  google:
    id:

## search
search:
  using: hexo_generator_search
  baidu:
    verified: true # false使用极速搜索，无需验证站点；true使用自定义搜索，可以定制高级功能
    site: www.ieclipse.cn # 你的站点名称，极速搜索要用到
    sid: "11812712506721118476" #如不清楚，将baidu_search_script.swig里面的script全部替换掉
    domain: //search.ieclipse.cn #CNAME到zhannei.baidu.com的域名，未配置留空
  hexo_generator_search: # see hexo_generator_search plugin config

rss: atom.xml

# icp
icp: 苏ICP备15019510号

## css
node_sass:
  outputStyle: nested

# grid layout
layout:
  index: # index some to post.
    main: col-sx-12 col-sm-8 col-md-9 col-lg-9
    widgets: col-sx-12 col-sm-4 col-md-3 col-lg-3 #hidden-xs
  page: #common page
    main: col-sx-12 col-sm-8 col-md-9 col-lg-9
    toc: col-sx-12 col-sm-4 col-md-3 col-lg-3 hidden-xs
  p: #project
    sidebar: col-sx-12 col-sm-12 col-md-2 col-lg-2
    main: col-sx-12 col-sm-8 col-md-8 col-lg-8
    toc: col-sx-2 col-sm-2 col-md-2 col-lg-2 hidden-xs
  d: #donates
    main: col-sx-12 col-sm-8 col-md-9 col-lg-9
    top: col-sx-6 col-sm-4 col-md-3 col-lg-3
