      <input type="text" name="word" id="bdcsMain" class="form-control primary" aria-label="..." placeholder="{{ _p('widget.search')}}">
		<input name="tn" type="hidden" value="SE_zzsearchcode_shhzc78w">
                <input name="cl" type="hidden" value="3">
                <input name="ct" type="hidden" value="2097152">
                <input name="si" type="hidden" value="ieclipse.cn">
		<input name="ie" type="hidden" value="utf-8">
