      <input type="text" name="word" id="bdcsMain" class="form-control primary" aria-label="..." placeholder="{{ _p('widget.search')}}">
		<input name="tn" type="hidden" value="SE_zzsearchcode_shhzc78w">
                <input name="cl" type="hidden" value="3">
                <input name="ct" type="hidden" value="2097152">
                <input name="si" type="hidden" value="ieclipse.cn">
		<input name="ie" type="hidden" value="utf-8">
    <script type="text/javascript">(function(){document.write(unescape('%3Cdiv id="bdcs"%3E%3C/div%3E'));var bdcs = document.createElement('script');bdcs.type = 'text/javascript';bdcs.async = true;bdcs.src = 'http://znsv.baidu.com/customer_search/api/js?sid=14175568865013380132' + '&plate_url=' + encodeURIComponent(window.location.href) + '&t=' + Math.ceil(new Date()/3600000);var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(bdcs, s);})();</script>