
  <div class="fab" style="bottom: 45px; right: 24px;">
    <ul class="top-expand" id="top-expand">
      <li><a class="fab-item large bg-red white" href="#top"><i class="icon nova-top"></i></a></li>
      <li><a class="fab-item large bg-yellow white" href="http://www.jiathis.com/share?uid={{theme.share.jiathis.uid}}" target="_blank"><i class="icon nova-share"></i></a></li>
    </ul>
    <a class="fab-item large bg-red white" onclick="$('#top-expand').toggle();">
      <i class="icon nova-list-ul"></i>
    </a>
  </div>