<footer id="footer">
  <div class="divider"></div>
  <div>&nbsp;</div>
  <div class="inner text-center">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <a href="http://ieclipse.cn/" target="_blank">{{ config.author }}</a> powered by <a href="http://hexo.io" target="_blank">Hexo</a> Theme <a href="https://github.com/Jamling/hexo-theme-nova" target="_blank">nova</a><br>
      Documentation licensed under <a href="http://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>.
    </div>
    <div>
      <a href="http://www.miitbeian.gov.cn" target="_blank">{{theme.icp}}</a>
    </div>
  </div>
</footer>
