
  <div class="fixed-action-btn click-to-toggle" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large red">
      <i class="icon nova-list-ul"></i>
    </a>
    <ul>
      <li><a class="btn-floating btn-large red" href="#top"><i class="icon nova-top"></i></a></li>
      <li><a class="btn-floating btn-large yellow darken-1" href="http://www.jiathis.com/share?uid={{theme.share.jiathis.uid}}" target="_blank"><i class="icon nova-share"></i></a></li>
    </ul>
  </div>